from app.database import Base
from app.models.user import User
from app.models.image import Image
from app.models.admin import Admin
from app.models.course_activity import CourseActivity
from app.models.course import Course
from app.models.department import Department
from app.models.faculty import Faculty
from app.models.major import Major
from app.models.student import Student
from app.models.student_course import StudentCourse
from app.models.teacher import Teacher
from app.models.teacher_course import TeacherCourse
