"""modified course model

Revision ID: 3fde5921b796
Revises: 5a1a5bac987c
Create Date: 2025-05-25 22:13:56.384477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fde5921b796'
down_revision: Union[str, None] = '5a1a5bac987c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_courses_name', table_name='courses')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_courses_name', 'courses', ['name'], unique=True)
    # ### end Alembic commands ###
