"""your migration message

Revision ID: 5a1a5bac987c
Revises: 99197f5732f5
Create Date: 2025-05-25 22:12:39.621501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a1a5bac987c'
down_revision: Union[str, None] = '99197f5732f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_courses_code', table_name='courses')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_courses_code', 'courses', ['code'], unique=True)
    # ### end Alembic commands ###
