"""update data model

Revision ID: efa793a576f0
Revises: b3e7e9d0fb02
Create Date: 2025-05-19 00:55:12.201917

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efa793a576f0'
down_revision: Union[str, None] = 'b3e7e9d0fb02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('instructor_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'courses', 'users', ['instructor_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'courses', type_='foreignkey')
    op.drop_column('courses', 'instructor_id')
    # ### end Alembic commands ###
